"""initial revision

Revision ID: 1796ded87896
Revises:
Create Date: 2025-01-11 16:36:22.308500

"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1796ded87896"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company")),
    )
    op.create_table(
        "department",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("head_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
            name=op.f("fk_department_company_id_company"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department")),
    )
    op.create_index(
        op.f("ix_department_company_id"), "department", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_department_head_id"), "department", ["head_id"], unique=False
    )
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("middle_name", sa.String(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["company.id"], name=op.f("fk_employee_company_id_company")
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
            name=op.f("fk_employee_department_id_department"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee")),
    )
    op.create_index(
        op.f("ix_employee_company_id"), "employee", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_employee_department_id"), "employee", ["department_id"], unique=False
    )
    op.create_table(
        "user_company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
            name=op.f("fk_user_company_company_id_company"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_company")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_company_user_id")),
    )
    op.create_index(
        op.f("ix_user_company_company_id"), "user_company", ["company_id"], unique=False
    )
    op.create_foreign_key(op.f('fk_department_head_id_employee'), 'department', 'employee', ['head_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_company_company_id"), table_name="user_company")
    op.drop_table("user_company")
    op.drop_index(op.f("ix_employee_department_id"), table_name="employee")
    op.drop_index(op.f("ix_employee_company_id"), table_name="employee")
    op.drop_table("employee")
    op.drop_index(op.f("ix_department_head_id"), table_name="department")
    op.drop_index(op.f("ix_department_company_id"), table_name="department")
    op.drop_table("department")
    op.drop_table("company")
    # ### end Alembic commands ###
